name: PR validation

on:
  pull_request:
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install Cypress
        run: npm install cypress

      - name: Update npm
        run: npm install -g npm

      - name: Update dependencies
        run: npm i


      - name: run cypress tests
        uses: cypress-io/github-action@v5
        with:
          record: false
