name: Scheduled Cypress Tests

on:
  # This allows you to kick off this workflow manually
  workflow_dispatch:

  schedule:
    # Runs every Monday at 4:00 AM EST
    - cron: '00 9 * * 1'

jobs:
  nightly:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Match the version used in your project
          cache: 'npm'

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install dependencies
        run: npm ci

      - name: Cypress nightly tests 🌃
        uses: cypress-io/github-action@v5
        with:
          start: npm start
          wait-on: 'http://localhost:4200'
          wait-on-timeout: 300 # Timeout in seconds, adjust as necessary
          record: true
          tag: scheduled
        env:
          # Pass the Cypress Cloud record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
